'use client';
import { useRouter } from 'next/navigation';
import { Fragment } from 'react';
import './globals.scss';
import { Inter } from 'next/font/google';
import Header from '@/layout/Header';
import Footer from '@/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
    const router = useRouter();

    const showHeader = router.pathname === '/signup' ? false : true;

    return (
        <Fragment>
            <html lang="en">
                <body className={inter.className}>
                    {showHeader && <Header />}
                    <main>{children}</main>
                    <Footer />
                </body>
            </html>
        </Fragment>
    );
}
